global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoPlatformApp.DataContracts;
global using UnoPlatformApp.DataContracts.Serialization;
global using UnoPlatformApp.Models;
global using UnoPlatformApp.Presentation;
global using UnoPlatformApp.Services.Caching;
global using UnoPlatformApp.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
